/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ass;

import java.util.Random;
import java.util.Scanner;

/**
 *
 * @author Vamshi Bandla
 */
public class FrameDesign extends javax.swing.JFrame {

    /**
     * Creates new form FrameDesign
     */
    public FrameDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Optimal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Frame_Size");
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("page_Size");
        jScrollPane3.setViewportView(jTextArea3);

        jButton2.setText("LRU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Second_c");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("FIFO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(191, 191, 191)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       // optimal var = new optimal();
         jTextArea1.setText(" "); 
         String text = jTextField1.getText();
	   // textArea.append(text + "\n");
	 jTextField1.selectAll();
    //    Scanner in = new Scanner(System.in);
         String tex1 = jTextField2.getText();
         jTextField2.selectAll();
        Random R = new Random();
        System.out.println("Enter the no.of Frames");
//        text =  " "
        int fram = Integer.parseInt(text);
        System.out.println("Enter the no.of Pages");
        int pag = Integer.parseInt(tex1);
        int[] a = new int[1000];
        int range = 10;
        for(int j = 0; j<pag;j++)
        {
            a[j] = R.nextInt(range - 0) + 1;
           
        }
        jTextArea1.append("input\n");
        for(int j = 0;j<pag;j++)
        {
             String mn = a[j] + " ";
            jTextArea1.append(mn + " ");
        }
       // System.out.print();
        System.out.println();
        optimal op = new optimal();
        op.setvalues(a,fram,pag);
     int   tr = op.code();
      //  int pl = var.fault;
        System.out.println(tr);
        String kk = " " + tr;
        jTextArea1.append("\nFauts  : "+ kk);
        jTextArea1.append("\noutput\n:" + op.st) ;
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //LRU var1 = new LRU();
          jTextArea1.setText(" "); 
         String text = jTextField1.getText();
	   // textArea.append(text + "\n");
	 jTextField1.selectAll();
    //    Scanner in = new Scanner(System.in);
         String tex1 = jTextField2.getText();
         jTextField2.selectAll();
         Random R = new Random();
         System.out.println("Enter the no.of Frames");
//        text =  " "
         int fram = Integer.parseInt(text);
         System.out.println("Enter the no.of Pages");
         int pag = Integer.parseInt(tex1);
         int[] a = new int[1000];
         int range = 10;
         for(int j = 0; j<pag;j++)
         {
            a[j] = R.nextInt(range - 0) + 1;
           
         }
         jTextArea1.append("input : \n");
         for(int j = 0;j<pag;j++)
         {
             String mn = a[j] + " ";
            jTextArea1.append(mn + " ");
         }
         LRU var1 = new LRU();
         var1.setvalues(a,fram,pag);
         int my = var1.code();
         jTextArea1.append("\nFaults :" + my);
        jTextArea1.append(" \noutput:\n" + var1.st);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //LRU var1 = new LRU();
         jTextArea1.setText(" "); 
         String text = jTextField1.getText();
	   // textArea.append(text + "\n");
	 jTextField1.selectAll();
    //    Scanner in = new Scanner(System.in);
         String tex1 = jTextField2.getText();
         jTextField2.selectAll();
         Random R = new Random();
         System.out.println("Enter the no.of Frames");
//        text =  " "
         int fram = Integer.parseInt(text);
         System.out.println("Enter the no.of Pages");
         int pag = Integer.parseInt(tex1);
         int[] a = new int[1000];
         int range = 10;
         for(int j = 0; j<pag;j++)
         {
            a[j] = R.nextInt(range - 0) + 1;
           
         }
         jTextArea1.append("input : \n");
         for(int j = 0;j<pag;j++)
         {
             String mn = a[j] + " ";
            jTextArea1.append(mn + " ");
         }
         Secondc var2 = new Secondc();
            var2.setvalues(a,fram,pag);
          //  var2.run();
          int my = var2.run();
         jTextArea1.append("\nFaults :" + my);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         jTextArea1.setText(" "); 
         String text = jTextField1.getText();
	   // textArea.append(text + "\n");
	 jTextField1.selectAll();
    //    Scanner in = new Scanner(System.in);
         String tex1 = jTextField2.getText();
         jTextField2.selectAll();
         Random R = new Random();
         System.out.println("Enter the no.of Frames");
//        text =  " "
         int fram = Integer.parseInt(text);
         System.out.println("Enter the no.of Pages");
         int pag = Integer.parseInt(tex1);
         int[] a = new int[1000];
         int range = 10;
         for(int j = 0; j<pag;j++)
         {
            a[j] = R.nextInt(range - 0) + 1;
           
         }
         jTextArea1.append("input : \n");
         for(int j = 0;j<pag;j++)
         {
             String mn = a[j] + " ";
            jTextArea1.append(mn + " ");
         }
        jTextArea1.append("\n");
        FIFO var3 = new FIFO();
        var3.setvalues(a, fram, pag);
        var3.code();
    
     
        
        int[] ag = new int[1000];
        ag = var3.aaa;
        String stp = var3.st;   
        System.out.print(stp);
        for(int d = 0 ;d<fram;d++)
        {
            String ss = " " + ag[d];
       // jTextArea1.append(ss);
        }
        
        jTextArea1.append("\n");
        jTextArea1.append("Fautls\n: " +  " " + var3.fault);
        jTextArea1.append("\noutput\n");
        jTextArea1.append(stp);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDesign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
